### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by dpsanders** [complexvariables/ComplexRegions.jl#2]
I suggest adding an explicit `using ComplexRegions` to the first example in the docs.

Also remove / fix this:
```
/home/travis/.julia/packages/GR/ZI5OE/src/../deps/gr/bin/gksqt: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
connect: Connection refused
GKS: can't connect to GKS socket application
Did you start 'gksqt'?

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine AC
```

Part of JOSS review @ https://github.com/openjournals/joss-reviews/issues/1811

**Comment by dpsanders** [comment]
And `using Plots`.

Basically the examples should be copyable-and-pastable.

**Comment by dpsanders** [comment]
Remove `;` from `plot!(c)` so that the plot actually appears.

**Comment by tobydriscoll** [comment]
I don't know what's causing the "connection refused" errors, though it's obviously in the Travis configuration that I set up using Documenter. It isn't happening with ComplexValues, so maybe comparing them will turn up something. Since the graphics were coming out anyway, I didn't make it a high priority. 

If I leave the semicolons off of the plot commands, it adds a cryptic text message about the plot object to the output for the page. Do you know how to prevent that?

**Comment by tobydriscoll** [comment]
The GKS issue has been addressed, and I removed semicolons from the doc plotting commands.
