### ISSUE TITLE
Meaning of `/` -- use broadcast instead?

### ISSUE THREAD

**Issue by dpsanders** [complexvariables/ComplexRegions.jl#3]
From the point of view of Julia, it seems strange to define e.g. `1 /  ℓ`, where `ℓ` is a line.
Since  `ℓ` is a set, it would maybe be more natural to think about the broadcasted version, `1 ./  ℓ`.

Part of JOSS review @ https://github.com/openjournals/joss-reviews/issues/1811

**Comment by tobydriscoll** [comment]
I think of broadcasting as applying to iterable collections. 

An alternative analogy would be a vector. Obviously `2v` and `2.*v` have identical effects on a `Vector`, but the former holds up as scaling a vector in infinite-dimensional space, while the notion of broadcasting becomes shakier. Conversely, `v.+2` is required over `v+2` because the notion of adding vector and scalar is not a strong one conceptually.

**Comment by dpsanders** [comment]
I see what you mean, but I am thinking about it as "apply the operation to all elements of the *set*".

For example, does it make sense to define a function like `f(z) = z^2 + 1 / z`  and then apply it to a `Line`?

**Comment by tobydriscoll** [comment]
It's not unusual in complex analysis to speak of transformations mapping curves to curves, or regions to regions. Perhaps it's because of the outsize role played by conformal maps. 

When I use `broadcast`, I expect it to work for any scalar-valued function requiring a scalar, including functions I define myself. That gets really complicated here. For instance, the `abs` function maps scalar to scalar, but in aggregate it maps a complex contour to some multiply-covered interval on the real line. At a minimum I'd have to dispatch `broadcast` on curve and region types, examine the function being broadcast, and error out if it wasn't on the approved list. I assume it could be done, but it sounds very clunky. And I don't know how all this is supposed to interact with the idea of dot fusion.

I don't see what is to be gained here. If you can point me to an example of a broadcast operator being used on uncountable collections, then I would better grasp how it would all work.

**Comment by dpsanders** [comment]
Yes I see your point. OK, it was probably ill-considered on my part. 
Thanks for the discussion.
